routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProvincesController;
use App\Http\Controllers\DistrictsController;
use App\Http\Controllers\SubDistrictsController;
use App\Http\Controllers\VillagesController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('province', ProvincesController::class);
Route::resource('district', DistrictsController::class);
Route::resource('subdistrict', SubDistrictsController::class);
Route::resource('village', VillagesController::class);

app/Models/Districts.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Districts extends Model
{
    use HasFactory;
    protected $table = 'districts';
    protected $fillable = [
        'province_id','name', 'slug'
    ];

    public function province()
    {
        return $this->belongsTo(Provinces::class);
    }

    public function subdistricts()
    {
        return $this->hasMany(Subdistrict::class);
    }

    public function villages()
    {
        return $this->hasMany(Villages::class);
    }


}

app/Http/Controllers/DistrictsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Provinces;
use App\Models\Districts;
use Illuminate\Support\Str;
class DistrictsController extends Controller
{
    public function index()
    {
        $districts = Districts::with('province')->latest()->paginate(10);
        // dd($districts);
        return view('district.index', compact('districts'));
    }

    public function create()
    {
        $provinces = Provinces::get();
        return view('district.create', compact('provinces'));
    }

    public function store(Request $request)
    {
        // dd($request);
        $this->validate($request, [
            'province_id' => 'required',
            'name'     => 'required'
        ]);

        //slug
        $slug = $request->slug ?? Str::slug($request->name, '-');
        $districts = Districts::create([
            'province_id' => $request->province_id,
            'name'     => $request->name,
            'slug'   => $slug
        ]);

        if($districts){
            //redirect dengan pesan sukses
            return redirect()->route('district.index')->with(['success' => 'Data Berhasil Disimpan!']);
        }else{
            //redirect dengan pesan error
            return redirect()->route('district.index')->with(['error' => 'Data Gagal Disimpan!']);
        }
    }

}

resources/views/district/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tambah Data Province</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body style="background: lightgray">

    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <form action="{{ route('district.store') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label for="province">Name Province</label>
                                <select name="province_id" id="province" class="form-control">
                                    <option selected disabled>Pilih Provinsi :</option>
                                    @foreach ($provinces as $province)
                                    <option value="{{ $province->id }}">{{ $province->name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">Name Districts</label>
                                <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" placeholder="Insert Your Name Province" required>
                            
                                <!-- error message untuk title -->
                                @error('province')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                            <button type="submit" class="btn btn-md btn-primary">SIMPAN</button>
                            <button type="reset" class="btn btn-md btn-warning">RESET</button>

                        </form> 
                    </div>
                </div>
            </div>
        </div>
    </div>
    
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

resources/views/district/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Data Districts</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
</head>
<body style="background: lightgray">

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <a href="{{ route('district.create') }}" class="btn btn-md btn-success mb-3">TAMBAH District</a>
                        <table class="table table-bordered">
                            <thead>
                              <tr>
                                <th scope="col">Name Province</th>
                                <th scope="col">Name District</th>
                                <th scope="col">Slug</th>
                              </tr>
                            </thead>
                            <tbody>
                              @forelse ($districts as $district)
                                <tr>
                                    <td>{{ $district->province->name }}</td>
                                    <td>{{ $district->name }}</td>
                                    <td>{{ $district->slug }}</td>
                                    <td class="text-center">
                                        <form onsubmit="return confirm('Apakah Anda Yakin ?');" action="{{ route('district.destroy', $district->id) }}" method="POST">
                                        <a href="{{ route('district.edit', $district->id) }}" class="btn btn-sm btn-primary">EDIT</a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-sm btn-danger">HAPUS</button>
                                        </form>
                                    </td>
                                </tr>
                              @empty
                                  <div class="alert alert-danger">
                                      Data districts belum Tersedia.
                                  </div>
                              @endforelse
                            </tbody>
                          </table>  
                          {{ $districts->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script>
        //message with toastr
        @if(session()->has('success'))
        
            toastr.success('{{ session('success') }}', 'BERHASIL!'); 

        @elseif(session()->has('error'))

            toastr.error('{{ session('error') }}', 'GAGAL!'); 
            
        @endif
    </script>

</body>
</html>