routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProvincesController;
use App\Http\Controllers\DistrictsController;
use App\Http\Controllers\SubDistrictsController;
use App\Http\Controllers\VillagesController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('province', ProvincesController::class);
Route::resource('district', DistrictsController::class);
Route::resource('subdistrict', SubDistrictsController::class);
Route::resource('village', VillagesController::class);

app/Models/Villages.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Villages extends Model
{
    use HasFactory;
    protected $table = 'villages';
    protected $fillable = ['name', 'slug', 'province_id', 'district_id', 'subdistrict_id'];

    public function province()
    {
        return $this->belongsTo(Provinces::class);
    }

    public function district()
    {
        return $this->belongsTo(Districts::class);
    }

    public function subdistrict()
    {
        return $this->belongsTo(Subdistricts::class);
    }

}

app/Http/Controllers/VillagesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Provinces;
use App\Models\Districts;
use App\Models\SubDistricts;
use App\Models\Villages;
use Illuminate\Support\Str;
class VillagesController extends Controller
{
    public function index()
    {
        $villages = Villages::with('province', 'district', 'subdistrict')->latest()->paginate(10);
        // dd($districts);
        return view('village.index', compact('villages'));
    }

   

}

resources/views/village/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Data Districts</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
</head>
<body style="background: lightgray">

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <a href="{{ route('village.create') }}" class="btn btn-md btn-success mb-3">TAMBAH Village</a>
                        <table class="table table-bordered">
                            <thead>
                              <tr>
                                <th scope="col">Province</th>
                                <th scope="col">District</th>
                                <th scope="col">SubDistrict</th>
                                <th scope="col">Village</th>
                                <th scope="col">Slug</th>
                              </tr>
                            </thead>
                            <tbody>
                              @forelse ($villages as $village)
                                <tr>
                                    <td>{{ $village->province->name }}</td>
                                    <td>{{ $village->district->name }}</td>
                                    <td>{{ $village->subdistrict->name }}</td>
                                    <td>{{ $village->name }}</td>
                                    <td>{{ $village->slug }}</td>
                                    <td class="text-center">
                                        <form onsubmit="return confirm('Apakah Anda Yakin ?');" action="{{ route('village.destroy', $village->id) }}" method="POST">
                                        <a href="{{ route('village.edit', $village->id) }}" class="btn btn-sm btn-primary">EDIT</a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-sm btn-danger">HAPUS</button>
                                        </form>
                                    </td>
                                </tr>
                              @empty
                                  <div class="alert alert-danger">
                                      Data districts belum Tersedia.
                                  </div>
                              @endforelse
                            </tbody>
                          </table>  
                          {{ $villages->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script>
        //message with toastr
        @if(session()->has('success'))
        
            toastr.success('{{ session('success') }}', 'BERHASIL!'); 

        @elseif(session()->has('error'))

            toastr.error('{{ session('error') }}', 'GAGAL!'); 
            
        @endif
    </script>

</body>
</html>